read_demonstration: read_demonstration.cpp
	g++ -std=c++11 -o read_demonstration read_demonstration.cpp
	./read_demonstration

file_writer:  main.cpp file_io.cpp file_io.h
	g++ -std=c++11 -o file_writer main.cpp file_io.cpp
