bits: bits.cpp
	g++ -std=c++11 -o bits bits.cpp

bits2: bits2.cpp
	g++ -std=c++11 -o bits2 bits2.cpp

bits3: bits3.cpp 
	g++ -std=c++11 -o bits3 bits3.cpp

run: bits bits2 bits3
	./bits
	./bits2
	./bits3


